WIDTH = 64*8
HEIGHT = 64*8
ADDITIONAL_HEIGHT = 64
ADDITIONAL_WIDTH = 64
WIDTH_TOTAL = WIDTH + 2*ADDITIONAL_WIDTH
HEIGHT_TOTAL = HEIGHT + 2*ADDITIONAL_HEIGHT
SQUARE_SIZE = 64
MAX_FPS = 15

BASE_DIMENSION = 8
ADDITIONAL_DIMENSION = 2

