BASE_DIMENSION = 8
SQUARE_SIZE = 64
ADDITIONAL_DIMENSION = 2

WIDTH = SQUARE_SIZE*BASE_DIMENSION
HEIGHT = SQUARE_SIZE*BASE_DIMENSION
ADDITIONAL_HEIGHT = SQUARE_SIZE
ADDITIONAL_WIDTH = SQUARE_SIZE
WIDTH_TOTAL = WIDTH + ADDITIONAL_DIMENSION*ADDITIONAL_WIDTH
HEIGHT_TOTAL = HEIGHT + ADDITIONAL_DIMENSION*ADDITIONAL_HEIGHT
MAX_FPS = 15

AI_DEPTH = 2